"""Handler: discover authoritative reference domains for one client.

Reads :
- client.apps['client_brief']['industry'] (required — generated by
  generate_client_brief)

Writes :
- client.apps['trust_sources'] = {domains, details, industry_text,
  industry_hash, discovered_at, sources_count, extra_domains}

Triggered :
- Automatically chained from generate_client_brief on success (best-effort,
  idempotent — see chain in generate_client_brief.py)
- Manually via API for existing clients (seed flow) or refresh requests

Idempotent — `services.trust_sources.is_discovery_stale()` short-circuits if
the cached payload is fresh AND industry_text hasn't changed. To force
refresh, send `{"force": True}` in the job payload.

Cost : 1 OpenAI Responses API web_search call (~$0.02) per refresh. With the
default 90-day TTL that's ~$0.08/year/client — not credit-debited (system-
triggered infrastructure call, not user-facing content gen).

v1 limitation : language defaults to "fr" (matches sen-ai v1 lock to French
dermo-cosmetic). Override via job_payload['language'] for other markets — v2
will derive from client.config or scan locale.
"""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session
from sqlalchemy.orm.attributes import flag_modified

from config import settings
from services.trust_sources import (
    build_trust_sources_payload,
    discover_trust_sources,
    is_discovery_stale,
)

logger = logging.getLogger(__name__)


def execute(job_payload: dict, scan_id: str | None, db: Session) -> dict:
    """Discover and persist the trust sources for one client.

    job_payload :
      - client_id (required)
      - force (optional bool) — bypass staleness check, re-discover anyway
      - language (optional str) — override default "fr" (ISO code, lower)

    scan_id : unused (workspace-scoped, no scan billing).
    """
    from models import Client

    client_id = job_payload.get("client_id")
    if not client_id:
        raise ValueError("discover_trust_sources requires client_id in job payload")

    force = bool(job_payload.get("force"))
    language = (job_payload.get("language") or "fr").strip().lower()

    client = db.query(Client).filter(Client.id == client_id).first()
    if not client:
        raise ValueError(f"Client {client_id} not found")

    apps = client.apps or {}
    brief = apps.get("client_brief") or {}
    industry = (brief.get("industry") or "").strip()
    if not industry:
        logger.warning(
            f"Client {client_id} has no client_brief.industry — cannot discover "
            f"trust sources (generate_client_brief must run first)"
        )
        return {"status": "skipped", "reason": "missing_industry"}

    if not force and not is_discovery_stale(apps, industry):
        logger.info(
            f"Trust sources for client {client_id} still fresh "
            f"(industry={industry!r}) — skipping discovery"
        )
        return {"status": "skipped", "reason": "fresh"}

    # Cap-then-call : trust-sources discovery runs ~$0.03 (single OpenAI
    # web_search). Project $0.05 for safety.
    from services.llm_budget import assert_within_budget
    assert_within_budget(client_id, db, projected_cost_usd=0.05)

    if not settings.openai_api_key:
        logger.warning(
            "OPENAI_API_KEY not configured — cannot discover trust sources"
        )
        return {"status": "skipped", "reason": "no_api_key"}

    sources = discover_trust_sources(
        industry=industry,
        language=language,
        openai_api_key=settings.openai_api_key,
        model="gpt-4.1-mini",
    )

    if not sources:
        # Discovery failed (OpenAI error, parse failure, empty result). Don't
        # write an empty payload — leave the prior value (if any) intact and
        # let the caller retry later. get_trust_sources_for_client() will
        # fall back to UNIVERSAL_REFERENCES in the meantime.
        logger.warning(
            f"Discovery returned 0 sources for client {client_id} "
            f"(industry={industry!r}) — leaving prior payload unchanged"
        )
        return {"status": "empty", "sources_count": 0}

    # Preserve any user-added extras from the prior payload
    prior = apps.get("trust_sources") or {}
    prior_extras = prior.get("extra_domains") or []

    payload = build_trust_sources_payload(industry, sources, prior_extras=prior_extras)
    apps["trust_sources"] = payload
    client.apps = apps
    flag_modified(client, "apps")
    db.commit()

    logger.info(
        f"Trust sources stored for client {client_id} "
        f"(industry={industry!r}): {payload['sources_count']} domains "
        f"({', '.join(payload['domains'][:5])}...)"
    )

    return {
        "status": "ok",
        "sources_count": payload["sources_count"],
        "industry": industry,
        "domains_preview": payload["domains"][:5],
    }
